  var lyrics4_output = [
"I'm really stepping up my game",
"These bitches gotta start paying me for this",
"Can't get no more free Randy",
"Got everything, I got everything",
"I cannot complain, I cannot",
"I don't even know how much I really made, I forgot, it's a lot",
"Fuck that, never mind what I got",
"Nigga don't watch that 'cause I —",
"Came up, that's all me, stay true, that's all me",
"No help, that's all me, all me for real",
"Came up, that's all me, stay true, that's all me",
"No help, that's all me, all me for real",
"Money on my mind, you should think the same",
"J's on, pinky ring—dogging these hoes, I need quarantine",
"In the same league, but we don't ball the same",
"(Ah) She want all the fame, I hear that shit all the time",
"She said she love me, I said",
"Baby girl, fall in line",
"Okay, made a million, off a dinner fork, watch me switch it up",
"Walked in",
"Ill nigga alert! Ill nigga alert!",
"You need that work, I got that work, got bitches in my condo",
"Just bought a shirt that cost a Mercedes-Benz car note",
"From the A to Toronto, we let the metal go off",
"And my dick so hard it make the metal detector go off",
"This that sauce, this that dressing",
"Givenchy, nigga God bless you",
"If having a bad bitch was a crime, I'd be arrested",
"Got everything, I got everything",
"I cannot complain, I cannot",
"I don't even know how much I really made, I forgot, it's a lot",
"Fuck that, never mind what I got",
"Nigga don't watch that 'cause I —",
"Came up, that's all me, stay true, that's all me",
"No help, that's all me, all me for real",
"Came up, that's all me, stay true, that's all me",
"No help, that's all me, all me for real",
"I touched down in '86, knew I was the man by the age of 6",
"I even fucked the girl that used to babysit",
"But that was years later on some crazy shit",
"I heard your new shit, nigga hated it",
"Damon Wayans, homie don't play that shit",
"I get paid a lot, you get paid a bit",
"And my latest shit is like a greatest hits",
"God damn, ain't no wishing over on this side",
"Y'all don't fuck with us, then we don't fuck with y'all",
"It's no different over on this side",
"God damn, should I listen to everybody or myself?",
"'Cause myself just told myself",
"You're the motherfucking man, you don't need no help",
"Cashing checks and I'm bigging up my chest",
"Y'all keep talking 'bout who next, but I'm about as big as it gets",
"I swear y'all just wasting y'all breath",
"I'm the light skinned Keith Sweat, I'mma make it last forever",
"It's not your turn 'cause I ain't done yet",
"Look, just understand that I'm on a roll like Cottonelle",
"I was made for all of this shit",
"And I'm on the road box office sales",
"I'm getting paid for all of this shit",
"Ask you to please excuse my table manners",
"I was making room for the table dancers",
"'Cause if we judging off your advances",
"Then I just got paid like eight advances, God damn",
"Got everything, I got everything",
"I cannot complain, I cannot",
"I don't even know how much I really made, I forgot, it's a lot",
"Fuck that, never mind what I got",
"Nigga don't watch that 'cause I —",
"Came up, that's all me, stay true, that's all me",
"No help, that's all me, all me for real",
"Came up, that's all me, stay true, that's all me—",
"Ho, shut the fuck up",
"I got way too much on my mental",
"I learn from what I've been through",
"I'm finna do what I didn't do",
"And still waking up like the rent's due",
"Not complicated, it's simple",
"I got sexy ladies, a whole Benz-full",
"And to them hoes I'm everything—everything but gentle",
"But I still take my time, man, I guess I'm just old fashioned",
"Wearing retro shit, that's old fashion",
"Nigga, see what I'm saying, no closed caption",
"I paint pics, see the shit, good sex, need to hit",
"Keep a broad on the floor year 'round like season tickets",
"I plead the fifth, drink a fifth, load the nine",
"Leave you split, in the half, smoke a half, need a zip",
"My new girl is on Glee and shit",
"Probably making more money than me and shit",
"I swear to God I got 99 problems but a bitch ain't one",
"I got 99 problems, getting rich ain't one",
"Like I got trust issues",
"I'm sorry for the people I've pushed out",
"I'm the type to have a bullet-proof condom",
"And still gotta pull out",
"But that's just me and I ain't perfect",
"I ain't a saint but I am worth it",
"If it's one thing, I am worth it",
"Niggas still hating but it ain't working",
"Lil' bitch",
"Oh me, oh me, oh my",
"I think I done fucked too many women from the 305",
"'Fore the end of this year",
"I'll do King of Diamonds 3 more times",
"Smoking on that kush all in our section",
"Like it's legalized",
"Girl, you can't always have your way",
"Sometimes it be like that",
"They don't really fuck with you like that",
"They ain't never did me like that",
"I just took my time, you got the shine",
"I let you eat like that",
"I been taught to never loan somebody",
"What you need right back",
"And I need that shit right back",
"I'm blessed than a muhfucka",
"Niggas been stressed than a muhfucka",
"Niggas getting nervous",
"Clutching they chests like a muhfucka",
"Damn that's a motherfucker",
"Tell the truth, I don't listen to you",
"Cause I don't like being lied to",
"And that ship won't sail",
"And that wind won't guide you",
"Daddy was in jail, we was talking through the window",
"Like a motherfucking drive-thru",
"That was back then, man",
"Now my niggas rich enough to do whatever I do",
"I got bands",
"Broke boys coming to me with their open hands",
"And I ain't trippin'",
"I'm just saying now everybody wanna be my friend",
"I finally fell in love",
"Now all these bitches wanna come and fuck up my plans",
"I'm just trying to be who I am",
"It's just something they will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"Same life, getting rich, whoa I got a fuckin' problem",
"Trying to flex up on young posty, we gon' tell them what's up",
"We gon' tour motherfucker, came up, I ain't lonely",
"Gotta problem Santiago, 45 by the gut",
"Post and 1st, we in the cut, we were smoking on the woods",
"And they think it smells good and they all want a puff",
"Said they see me at the show, they was in the front row",
"They wanna fuck, I told them bitches come and jump on my bus",
"We got molly and we got Xans",
"And we got drank and we got plants",
"And we got white and we got gas",
"And it's just something they will never understand",
"I got bands",
"Broke boys coming to me with their open hands",
"And I ain't trippin'",
"I'm just saying now everybody wanna be my friend",
"I finally fell in love",
"Now all these bitches wanna come and fuck up my plans",
"I'm just trying to be who I am",
"It's just something they will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They used to didn't love me now they calling me the man",
"Baby where are you going? Love, you know I got a plan",
"I can elevate your life, your life",
"Keep them niggas far away, they praying on my downfall",
"You don't fuck with me the long way so baby what you here for?",
"It could be so simple, meet me out in Frisco",
"Yeah yeah, yeah-hey",
"Calculate your steps and keep your circle small",
"Understand that nothing lasts forever",
"Glamorization of this lifestyle will leave you desperate",
"Yeah, yeah, yeah",
"I got bands",
"Broke boys coming to me with their open hands",
"And I ain't trippin'",
"I'm just saying now everybody wanna be my friend",
"I finally fell in love",
"Now all these bitches wanna come and fuck up my plans",
"I'm just trying to be who I am",
"It's just something they will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"They will never understand",
"All for the gram",
"Bitches love the gram",
"Oh wait shit",
"Brr brr",
"Brr brr brr",
"Skrr skrr",
"Roxanne",
"Roxanne",
"All she wanna do is party all night",
"Goddamn, Roxanne",
"Never gonna love me but it's alright",
"She think I'm an asshole",
"She think I'm a player",
"She keep running back though",
"Only cause I pay up",
"Roxanne",
"Roxanne",
"All she wanna do is party all night",
"Met her at a party in the hills, yeah",
"She just wanna do it for the thrill, yeah",
"Shorty drive a poodle with no top",
"But if I throw this money she gon' drop",
"She don't wait in lines if it's too long",
"She don't drive the whip unless the roof off",
"Only want to call when the cash out",
"Only take the pic when her ass out",
"She from",
"Malibu, Malibu",
"If you ain't gotta foreign then she laugh at you",
"Malibu, Malibu",
"Spending daddy's money with an attitude",
"Roxanne",
"Roxanne",
"All she wanna do is party all night",
"Goddamn, Roxanne",
"Never gonna love me but it's alright",
"She think I'm an asshole",
"She think I'm a player",
"She keep running back though",
"Only cause I pay up",
"Roxanne",
"Roxanne",
"All she wanna do is party all night",
"I just wanna have fun",
"In LA, yeah",
"Got no brakes, yeah",
"Living fast, Ricky Bobby",
"Shake and bake, yeah",
"See the chain? yeah",
"Issa lake, yeah",
"Swipe the chase, ooh",
"Now she wanna date, yeah",
"Straight to NOBU",
"On the coast ooh",
"Shorty only like cocaine and whole foods",
"Yeah",
"Snappin' all up on the gram",
"Ass going crazy",
"Now she wanna fuck me in the foreign",
"Going 80",
"Up in",
"Malibu, Malibu",
"If you ain't gotta foreign then she laugh at you",
"Malibu, Malibu",
"Spending daddy's money with an attitude",
"Roxanne",
"Roxanne",
"All she wanna do is party all night",
"Goddamn, Roxanne",
"Never gonna love me but it's alright",
"She think I'm an asshole",
"She think I'm a player",
"She keep running back though",
"Only cause I pay up",
"Roxanne",
"Roxanne",
"All she wanna do is party all night",
"I had a dream",
"I got everything I wanted",
"Not what you'd think",
"And if I'm being honest",
"It might have been a nightmare",
"To anyone who might care",
"Thought I could fly",
"So I stepped off the golden",
"Nobody cried",
"Nobody even noticed",
"I saw them standing right there",
"Kinda thought they might care",
"I had a dream",
"I got everything I wanted",
"But when I wake up, I see",
"You with me",
"And you say",
"As long as I'm here",
"No one can hurt you",
"Don't wanna lie here",
"But you can learn to",
"If I could change the way that you see yourself",
"You wouldn't wonder why you hear",
"They don't deserve you",
"I tried to scream",
"But my head was under water",
"They called me weak",
"Like I'm not just somebody's daughter",
"Could've been a nightmare",
"But it felt like they were right there",
"And it feels like yesterday was a year ago",
"But I don't wanna let anybody know",
"'Cause everybody wants something from me now",
"And I don't wanna let 'em down",
"I had a dream",
"I got everything I wanted",
"But when I wake up, I see",
"You with me",
"And you say",
"As long as I'm here",
"No one can hurt you",
"Don't wanna lie here",
"But you can learn to",
"If I could change the way that you see yourself",
"You wouldn't wonder why you hear",
"They don't deserve you",
"If I knew it all then, would I do it again?",
"Would I do it again?",
"If they knew what they said would go straight to my head",
"What would they say instead?",
"If I knew it all then, would I do it again?",
"Would I do it again?",
"If they knew what they said would go straight to my head",
"What would they say instead?",
"Never need a bitch, I'm what a bitch needs",
"Trying to find the one that can fix me",
"I've been dodging death in the six-speed",
"Amphetamine got my stomach feeling sickly",
"Yeah, I want it all now",
"I've been running through the pussy, need a dog pound",
"Hundred models getting faded in the compound",
"Trying to love me but they never get a pulse down",
"'Cause I'm heartless","And I'm back to my ways 'cause I'm heartless",
"All this money and this pain got me heartless",
"Low life for life 'cause I'm heartless",
"Said I'm heartless",
"Trying to be a better man but I'm heartless",
"Never be a wedding plan for the heartless",
"Low life for life 'cause I'm heartless",
"Said I'm heartless",
"So much pussy, it be falling out the pocket",
"Metro Boomin, turn this hoe into a mosh pit",
"Tesla pill got me flying like a cockpit",
"Yeah, I got her watching",
"Call me up, turn that pussy to a faucet",
"Duffel bags full of drugs and a rocket",
"Stix drunk but he never miss a target",
"Photoshoots, I'm a star now",
"I'm talkin' Time, Rolling Stone and Bazaar now",
"Selling dreams to these girls with their guard down",
"Seven years I've been swimming with the sharks now",
"'Cause I'm heartless","And I'm back to my ways cause I'm heartless",
"All this money and this pain got me heartless",
"Low life for life 'cause I'm heartless",
"Said I'm heartless",
"Tryna be a better man but I'm heartless",
"Never be a wedding plan for the heartless",
"Low life for life 'cause I'm heartless",
"I lost my heart and my mind",
"I tried to always do right",
"I thought I lost you this time",
"You just came back in my life",
"You never gave up on me",
"I'll never know what you see",
"I don't do well when alone",
"You hear it clearly in my tone",
"'Cause I'm heartless",
"And I'm back to my ways cause I'm heartless",
"All this money and this pain got me heartless",
"Low life for life 'cause I'm heartless",
"Said I'm heartless",
"Tryna be a better man but I'm heartless",
"Never be a wedding plan for the heartless",
"Low life for life 'cause I'm heartless",
"You know everybody been waiting on that Baby, man",
"I mean, it like ever since Baby on Baby dropped, man, like",
"(Ever since Baby on Baby dropped) You know",
"Ain't nobody drop shit",
"I needed some shit with some bop in it",
"I flew past a whip with that blunt in my mouth",
"While she swerving, that whip had a cop in it (Woo)",
"My bitch got good pussy, fly her across the country",
"I'll finish the show and I hop in it",
"I got me a millie, I did it legitly",
"I'm still with the shits, I'm a hot nigga ",
"Oh, you asking for pictures with niggas? (What)",
"What's yo name? Get the fuck out the spot nigga (Get the fuck)",
"Tryna figure which deal I'ma take",
"I woke up, couple mill' on my plate",
"I'm investing in real in the state",
"I just went gave my mama a hundred",
"Probably won't hear me open my mouth",
"'Less you hear me talking 'bout finding some money",
"As soon as I found it, I flipped that ",
"I'm a little bit different, they get it ",
"Know I'm stiff on a bitch and she dig it",
"Tryna find out why Baby ain't all in her mentions",
"No, she ain't get no DM from me",
"This rich nigga dick, it ain't free",
"She be throwing that ass, yeah, she good at it",
"Turn around when we fuck, make her look at it",
"I needed some shit with some bop in it",
"I flew past a whip with that blunt in my mouth",
"While she swerving, that whip had a cop in it ",
"My bitch got good pussy, fly her across the country",
"I'll finish the show and I hop in it",
"I got me a millie, I did it legitly",
"I'm still with the shits, I'm a hot nigga",
"I'm unorthodox than a muhfucka'",
"Aye, when you gone switch the flow? I thought you'd never ask",
"You niggas ain't fucking with me and ain't 'bout what the fuck",
"They be rapping 'bout with they lil' scary ass",
"But to each his own nigga",
"If you like it, I love it, no biggie",
"That boy say he get money, oh, really?",
"How much they just cut you a check for? A millie",
"I'm going back to Cali like Biggie",
"'Bout to go get a pound just to smoke",
"They told me to come work on my album",
"I'm tryna go find out the price on a boat",
"My lil' bitch act like Megan Thee Stallion",
"She ghetto and nasty, she driving the boat",
"All this shit that they making be boring",
"Give me something to bop while I ride with the pole",
"Here you go",
"I needed some shit with some bop in it",
"I flew past a whip with that blunt in my mouth",
"While she swerving, that whip had a cop in it",
"My bitch got good pussy, fly her across the country",
"I'll finish the show and I hop in it",
"I got me a millie, I did it legitly",
"I'm still with the shits, I'm a hot nigga",
"Aight, this shit for like, you know",
"The sophisticated ratchet hoe, you know",
"The ones that go to work by day then",
"You know, dance in the mirror by night",
"(Hah)","I needed some shit with some bop in it",
"I flew past a whip with that blunt in my mouth",
"While she swerving, that whip had a cop in it",
"My bitch got good pussy, fly her across the country",
"I'll finish the show and I hop in it",
"I got me a millie, I did it legitly",
"I'm still with the shits, I'm a hot nigga",
"Oh, you asking for pictures with niggas?",
"What's yo name? Get the fuck out the spot, nigga",
"Tryna figure which deal I'ma take",
"I woke up, couple mill on my plate" ];
